#!/bin/sh

# system stuff
apt-get --yes --force-yes upgrade 
apt-get --yes --force-yes update
apt-get --yes --force-yes build-essential

# apache
apt-get --yes --force-yes install apache2

# ruby enterprise edition
apt-get --yes --force-yes install zlib1g-dev
apt-get --yes --force-yes install libssl-dev
apt-get --yes --force-yes install libreadline5-dev
apt-get --yes --force-yes install libdbd-sqlite3-ruby1.8
apt-get --yes --force-yes install sqlite3
apt-get --yes --force-yes install libsqlite3-dev
wget http://rubyforge.org/frs/download.php/51100/ruby-enterprise-1.8.6-20090201.tar.gz
tar xzvf ruby-enterprise-1.8.6-20090201.tar.gz
./ruby-enterprise-1.8.6-20090201/installer --auto /opt/ruby

ln -nfs /opt/ruby/bin/ruby /bin/ruby
ln -nfs /opt/ruby/bin/gem /bin/gem
ln -nfs /opt/ruby/bin/rake /bin/rake
ln -nfs /opt/ruby/bin/irb /bin/irb
ln -nfs /opt/ruby/bin/rails /bin/rails
ln -nfs /opt/ruby/bin/passenger-status /bin/passenger-status

# update rails
gem install rails --no-ri --no-rdoc
# install git
apt-get --yes --force-yes install git-core

# set up passenger to allow apache to run a rails app
apt-get --yes --force-yes install apache2-prefork-dev
apt-get --yes --force-yes install libapr1-dev
cd /opt/ruby/bin/
./passenger-install-apache2-module --auto

touch /etc/apache2/conf.d/passenger
cat >> /etc/apache2/conf.d/passenger <<-EOF
LoadModule passenger_module /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.1.2/ext/apache2/mod_passenger.so
PassengerRoot /opt/ruby/lib/ruby/gems/1.8/gems/passenger-2.1.2
PassengerRuby /opt/ruby/bin/ruby
EOF

sudo rm /var/www/index.html
sudo touch /var/www/index.html
sudo cat >> /var/www/index.html <<-EOF
<html> <body> <h1> Server is go! </h1> </body> </html>
EOF

sudo rm /etc/apache2/sites-enabled/000-default
sudo touch /etc/apache2/sites-enabled/000-default
sudo cat >> /etc/apache2/sites-enabled/000-default <<-EOF
<VirtualHost *:80>
  ServerName localhost
  DocumentRoot /var/www

  <Directory "/var/www">
    Options FollowSymLinks
    AllowOverride None
    Order allow,deny
    Allow from all
  </Directory>

  ErrorLog /var/log/apache2/error.log
  CustomLog /var/log/apache2/access.log combined

</VirtualHost>
EOF

sudo /etc/init.d/apache2 restart


